name: address_sanitizer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      FC: gfortran-9
      CXX: g++-9

    steps:
    - name: install-dependencies
      run: |
        echo "/home/runner/mpich/bin" >> $GITHUB_PATH
        sudo apt-get update
        sudo apt-get install libmpich-dev
        sudo apt-get install doxygen
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
        sudo apt-get install libpng-dev
        sudo apt-get install libjpeg-dev
        python3 -m pip install gcovr

    - name: cache-esmf
      id: cache-esmf
      uses: actions/cache@v2
      with:
        path: ~/esmf
        key: esmf-${{ runner.os }}-8.0.1-2

    - name: build-esmf
      if: steps.cache-esmf.outputs.cache-hit != 'true'
      run: |
        set -x
        pushd ~
        export ESMF_DIR=~/esmf-ESMF_8_0_1
        wget https://github.com/esmf-org/esmf/archive/ESMF_8_0_1.tar.gz &> /dev/null && ls -l
        tar zxf ESMF_8_0_1.tar.gz && ls -l
        cd esmf-ESMF_8_0_1
        export ESMF_COMM=mpich3
        export ESMF_INSTALL_BINDIR=bin
        export ESMF_INSTALL_LIBDIR=lib
        export ESMF_INSTALL_MODDIR=mod
        export ESMF_COMPILER=gfortran
        export ESMF_INSTALL_PREFIX=~/esmf
        export ESMF_NETCDF=split
        export ESMF_NETCDF_INCLUDE=/usr/include
        export ESMF_NETCDF_LIBPATH=/usr/x86_64-linux-gnu
        make -j2
        make install

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/jasper
        key: jasper-${{ runner.os }}-2.0.22

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        set -x
        pwd
        wget https://github.com/jasper-software/jasper/archive/version-2.0.22.tar.gz &> /dev/null && ls -l
        tar zxf version-2.0.22.tar.gz && ls -l
        cd jasper-version-2.0.22
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/jasper
        make -j2
        make install

    - name: checkout-nceplibs
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS
        path: nceplibs

    - name: get-git-hash
      run: |
        cd nceplibs
        git rev-parse HEAD > hash.txt
        
    - name: cache-nceplibs-develop
      id: cache-nceplibs-develop
      uses: actions/cache@v2
      with:
        path: ~/nceplibs
        key: nceplibs-develop-${{ runner.os }}-${{ hashFiles('nceplibs/hash.txt') }}

    - name: build-nceplibs
      if: steps.cache-nceplibs-develop.outputs.cache-hit != 'true'
      run: |
        set -x
        export ESMFMKFILE=~/esmf/lib/esmf.mk
        cd nceplibs
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH='~;~/jasper' -DCMAKE_INSTALL_PREFIX='~/nceplibs' -DFLAT=ON
        make -j2
       
    - name: checkout-ufs-utils
      uses: actions/checkout@v2
      with: 
        path: ufs_utils

    - name: build-ufs-utils
      run: |
        export ESMFMKFILE=~/esmf/lib/esmf.mk
        cd ufs_utils
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH='~/jasper;~/nceplibs' -DCMAKE_Fortran_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
        make -j2
        make test
        export PATH="/home/runner/.local/bin:$PATH"
        gcovr -r .. --html-details -o test-coverage.html

    - uses: actions/upload-artifact@v2
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      with:
        name: test-coverage
        path: ufs_utils/build/*.html
