name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmpich-dev
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
        sudo apt-get install libpng-dev
        sudo apt-get install libjpeg-dev

    - name: checkout-esmf
      uses: actions/checkout@v2
      with:
       repository: esmf-org/esmf
       path: esmf
       ref: ESMF_8_0_1
    - name: cache-esmf
      id: cache-esmf
      uses: actions/cache@v2
      with:
        path: ~/esmf
        key: esmf-${{ runner.os }}-8.0.1

    - name: build-esmf
      if: steps.cache-esmf.outputs.cache-hit != 'true'
      run: |
        export ESMF_DIR=`pwd`/esmf
        cd esmf
        export ESMF_COMM=mpich3
        export ESMF_INSTALL_BINDIR=bin
        export ESMF_INSTALL_LIBDIR=lib
        export ESMF_INSTALL_MODDIR=mod
        export ESMF_COMPILER=gfortran
        export ESMF_INSTALL_PREFIX=~
        export ESMF_NETCDF=split
        export ESMF_NETCDF_INCLUDE=/usr/include
        export ESMF_NETCDF_LIBPATH=/usr/x86_64-linux-gnu
        make -j2
        make install

    - name: checkout-jasper
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-2.0.22
    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/jasper
        key: jasper-${{ runner.os }}-2.0.22

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~
        make -j2
        make install

    - name: checkout-nceplibs
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS
        path: nceplibs
        ref: v1.2.0
    - name: cache-nceplibs
      id: cache-nceplibs
      uses: actions/cache@v2
      with:
        path: ~/nceplibs
        key: nceplibs-${{ runner.os }}-1.2.0

    - name: build-nceplibs
      if: steps.cache-nceplibs.outputs.cache-hit != 'true'
      run: |
        export ESMFMKFILE=~/lib/esmf.mk
        cd nceplibs
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~ -DFLAT=ON
        make -j2
       
    - name: checkout-ufs-utils
      uses: actions/checkout@v2
      with: 
        path: ufs_utils

    - name: build-ufs-utils
      run: |
        export ESMFMKFILE=~/lib/esmf.mk
        cd ufs_utils
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=~
        make -j2


    
        
   

